version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    groups:
      bun-dependencies:
        patterns:
          - '*'
